set(CONFIG_SKIPLIST_COMMAND "${CMAKE_COMMAND}" -E chdir "${WKS_DIR}")

file(STRINGS "${SKIPLIST_FILE}" SKIPLIST)
list(LENGTH SKIPLIST N_SKIPLIST)
if(N_SKIPLIST EQUAL 0)
  set(CONFIG_SKIPLIST_COMMAND ${CONFIG_SKIPLIST_COMMAND} catkin config --no-skiplist)
  set(CONFIG_SKIPLIST_COMMAND_COMMENT "Clearing skiplist for ${WKS}")
else()
  set(CONFIG_SKIPLIST_COMMAND ${CONFIG_SKIPLIST_COMMAND} catkin config --skiplist ${SKIPLIST})
  list(JOIN SKIPLIST " " SKIPLIST_STR)
  set(CONFIG_SKIPLIST_COMMAND_COMMENT "Set skiplist for ${WKS}: ${SKIPLIST_STR}")
endif()

message(STATUS "${CONFIG_SKIPLIST_COMMAND_COMMENT}")
execute_process(
  COMMAND ${CONFIG_SKIPLIST_COMMAND}
  COMMAND_ERROR_IS_FATAL ANY
)
file(TOUCH "${SKIPLIST_STAMP}")
