# syntax=docker.io/docker/dockerfile:1.4
ARG _DEV_CONTAINERS_BASE_IMAGE=placeholder
FROM mcr.microsoft.com/devcontainers/cpp:ubuntu-22.04 AS dev_container_auto_added_stage_label
ARG EMAIL="devcontainer@mc-rtc-superbuild.com"
ARG NAME="mc_rtc devcontainer"

RUN export DEBIAN_FRONTEND=noninteractive

# Install latest cmake version
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null \
 && echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null \
 && apt update \
 && rm /usr/share/keyrings/kitware-archive-keyring.gpg \
 && apt-get install -y --no-install-recommends kitware-archive-keyring \
 && apt-get update \
 && apt-get install -y --no-install-recommends cmake

RUN apt-get -y install --no-install-recommends ccache python3-venv python3-pip ripgrep cmake


# Git now forces you to have an email
RUN git config --global user.email "${EMAIL}" && git config --global user.name "${NAME}"

USER vscode
# Add mc-rtc-superbuild to the build context
ADD .. mc-rtc-superbuild
WORKDIR /mc-rtc-superbuild
RUN ls

ENTRYPOINT ["/bin/bash", "-c"]

FROM $_DEV_CONTAINERS_BASE_IMAGE AS dev_containers_target_stage

USER root

COPY ./.devpod-internal/ /tmp/build-features/
RUN chmod -R 0755 /tmp/build-features && ls /tmp/build-features

RUN \
echo "_CONTAINER_USER_HOME=$(getent passwd vscode | cut -d: -f6)" >> /tmp/build-features/devcontainer-features.builtin.env && \
echo "_REMOTE_USER_HOME=$(getent passwd vscode | cut -d: -f6)" >> /tmp/build-features/devcontainer-features.builtin.env


RUN cd /tmp/build-features/0 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh



ARG _DEV_CONTAINERS_IMAGE_USER=root
USER $_DEV_CONTAINERS_IMAGE_USER