name: BaselineWalkingController Demo (Devcontainer)

on:
  repository_dispatch:
    types:
    - build-jammy
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        containerName: [baseline-walking-controller-dev]
        buildPreset: [bwc-tests]
    steps:
    - name: Configure ssh-agent 
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Check ssh-agent
      shell: bash
      run: |
          ssh-add -l

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: 'Docker: Build Standalone Release'
      shell: bash
      run: |
        cat .github/devcontainer/${{ matrix.containerName }}/Dockerfile
        echo "SSH_AUTH_SOCK = ${{ env.SSH_AUTH_SOCK }}"
        CONTAINER_NAME=ghcr.io/mc-rtc/baseline-walking-controller
        CONTAINER_TAG=${{ matrix.buildPreset }}-standalone-latest
        echo "CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
        echo "CONTAINER_TAG=${CONTAINER_TAG}" >> $GITHUB_ENV

        docker build . -f .github/devcontainer/${{ matrix.containerName }}/Dockerfile --ssh default --tag ${CONTAINER_NAME}:${CONTAINER_TAG} --build-arg CMAKE_PRESET=${{ matrix.buildPreset }} --build-arg BUILD_VERSION=${BUILD_VERSION}
        docker push ${CONTAINER_NAME}:${CONTAINER_TAG}

    - name: "Devcontainer: Prepare Dockerfile for Devcontainer Release Version"
      shell: bash
      run: |
          echo "FROM ${CONTAINER_NAME}:${CONTAINER_TAG}" > .github/devcontainer/${{ matrix.containerName }}/Dockerfile
          cat .github/devcontainer/${{ matrix.containerName }}/Dockerfile

    # Publish docker images
    - name: "Devcontainer: Build Release Version (main branch of official repository)"
      if: github.ref == 'refs/heads/setup/BaselineWalkingController' && github.repository == 'mc-rtc/mc-rtc-superbuild'
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/isri-aist/baseline-walking-controller
        imageTag: ${{ matrix.buildPreset }}-devcontainer-latest
        subFolder: .github/devcontainer/${{ matrix.containerName }}
        configFile: .github/devcontainer/${{ matrix.containerName }}/devcontainer.json
        push: always