name: Dispatch BaselineWalkingController
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch for tag
        run: |
          echo "Sending repository_dispatch event dispatch-baseline_walking_controller"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/isri-aist/mc-rtc-superbuild-private-ci/dispatches \
            -d "{\"event_type\": \"dispatch-baseline_walking_controller\" }"