name: CDADance Demo (Devcontainer)

on:
  repository_dispatch:
    types:
    - build-jammy
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # containerName: [cdadance-dev, cdadance-release]
        containerName: [cdadance-release]
    steps:
    - name: Configure ssh-agent 
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Check ssh-agent
      shell: bash
      run: |
          ssh-add -l

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: 'Build Standalone Release Docker Version'
      run: |
        cat .github/devcontainer/${{ matrix.containerName }}/Dockerfile
        docker build . -f .github/devcontainer/${{ matrix.containerName }}/Dockerfile --ssh default --tag ghcr.io/mc-rtc/${{ matrix.containerName }}:standalone-latest
        docker push ghcr.io/mc-rtc/${{ matrix.containerName }}:standalone-latest


    - name: "Prepare Dockerfile for Devcontainer Release Version"
      shell: bash
      run: |
          echo "FROM ghcr.io/mc-rtc/${{ matrix.containerName }}:standalone-latest" > .github/devcontainer/${{ matrix.containerName }}/Dockerfile
          cat .github/devcontainer/${{ matrix.containerName }}/Dockerfile

    # Publish cdadance-dev and cdadance-release docker images
    - name: Build Devcontainer Release Version (main branch of official repository)
      if: github.ref == 'refs/heads/demo/CDADance' && github.repository == 'mc-rtc/mc-rtc-superbuild'
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/mc-rtc/${{ matrix.containerName }}
        imageTag: devcontainer-latest
        subFolder: .github/devcontainer/${{ matrix.containerName }}
        configFile: .github/devcontainer/${{ matrix.containerName }}/devcontainer.json
        push: always

