name: Dispatch CDADance
on:
  push:
    tags:
    - v*
jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: Send repository dispatch for tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Sending repository_dispatch event dispatch-cdadance with tag: $TAG_NAME"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/isri-aist/mc-rtc-superbuild-private-ci/dispatches \
            -d "{\"event_type\": \"dispatch-cdadance\", \"client_payload\": {\"tag\": \"${TAG_NAME}\"} }"
