name: CI Ubuntu Jammy

on:
  repository_dispatch:
    types:
    - build-jammy
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    # Run on Sunday, Tuesday and Thursday nights
    - cron: '0 22 * * 0,1,4'

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        use-mc-rtc-apt-mirror: [ON, OFF]
        use-mc-rtc-apt-mirror-stable: [ON, OFF]
        exclude:
          - use-mc-rtc-apt-mirror: OFF
            use-mc-rtc-apt-mirror-stable: ON
    runs-on: ubuntu-22.04
    steps:
    - name: Maximize build space
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo docker image prune --all --force
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Workarounds
      shell: bash
      run: |
        sudo apt-mark hold grub-efi-amd64-signed
    - name: Bootstrap
      shell: bash
      run: |
        ./utils/bootstrap-linux.sh
    - name: Install system dependencies
      shell: bash
      run: |
        mkdir -p ${TMPDIR-/tmp}/build-mc-rtc
        cmake -S ${GITHUB_WORKSPACE} -B ${TMPDIR-/tmp}/build-mc-rtc -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVERBOSE_TEST_OUTPUT=ON -DUSE_MC_RTC_APT_MIRROR=${{ matrix.use-mc-rtc-apt-mirror }} -DUSE_MC_RTC_APT_MIRROR_STABLE=${{ matrix.use-mc-rtc-apt-mirror-stable }}
    - name: Install mc_rtc and related projects
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@example.com"
        cmake --build ${TMPDIR-/tmp}/build-mc-rtc --config RelWithDebInfo
