name: CI Windows

on:
  repository_dispatch:
    types:
    - build-windows
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    # Run on Sunday, Tuesday and Thursday nights
    - cron: '0 22 * * 0,1,4'

jobs:
  run:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Add GFortran DLL to path
      shell:  bash
      run: |
        echo "C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin" >> $GITHUB_PATH
    - name: Install system dependencies
      run: |
        cmake -S $Env:GITHUB_WORKSPACE -B C:/build-mc-rtc -DCMAKE_INSTALL_PREFIX=C:/devel/install -DPYTHON_BINDING=OFF -DVERBOSE_TEST_OUTPUT=OFF
    - name: Install mc_rtc and related projects
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@example.com"
        cmake --build C:/build-mc-rtc --config RelWithDebInfo
